
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CALL ENDTASK EQUALS IDENTIFIER LPAREN NUMBER RPAREN TASKprogram : statement_liststatement_list : statement_list statement\n| statementstatement : IDENTIFIER EQUALS NUMBERstatement : TASK IDENTIFIER LPAREN RPAREN statement_list ENDTASKstatement : CALL IDENTIFIER LPAREN RPAREN'
    
_lr_action_items = {'IDENTIFIER':([0,2,3,5,6,7,11,14,15,16,17,],[4,4,-3,9,10,-2,-4,4,-6,4,-5,]),'TASK':([0,2,3,7,11,14,15,16,17,],[5,5,-3,-2,-4,5,-6,5,-5,]),'CALL':([0,2,3,7,11,14,15,16,17,],[6,6,-3,-2,-4,6,-6,6,-5,]),'$end':([1,2,3,7,11,15,17,],[0,-1,-3,-2,-4,-6,-5,]),'ENDTASK':([3,7,11,15,16,17,],[-3,-2,-4,-6,17,-5,]),'EQUALS':([4,],[8,]),'NUMBER':([8,],[11,]),'LPAREN':([9,10,],[12,13,]),'RPAREN':([12,13,],[14,15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement_list':([0,14,],[2,16,]),'statement':([0,2,14,16,],[3,7,3,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement_list','program',1,'p_program','main.py',70),
  ('statement_list -> statement_list statement','statement_list',2,'p_statement_list','main.py',74),
  ('statement_list -> statement','statement_list',1,'p_statement_list','main.py',75),
  ('statement -> IDENTIFIER EQUALS NUMBER','statement',3,'p_statement_assign','main.py',83),
  ('statement -> TASK IDENTIFIER LPAREN RPAREN statement_list ENDTASK','statement',6,'p_statement_task_def','main.py',87),
  ('statement -> CALL IDENTIFIER LPAREN RPAREN','statement',4,'p_statement_task_call','main.py',91),
]
